// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALAsr4TVI5rHOjjEx6kUKuawoAuyuLfl4',
    appId: '1:354431250194:web:371ce6c9421f576d078dcb',
    messagingSenderId: '354431250194',
    projectId: 'jiffy-fuels',
    authDomain: 'jiffy-fuels.firebaseapp.com',
    storageBucket: 'jiffy-fuels.appspot.com',
    measurementId: 'G-5BH6SF2B8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRbIcVDslT8YRgAUsT_-f2ckMEXK_GWxo',
    appId: '1:354431250194:android:a264aa0bc613dbdb078dcb',
    messagingSenderId: '354431250194',
    projectId: 'jiffy-fuels',
    storageBucket: 'jiffy-fuels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASD-aApWDb_EpnpmVLIJPx93ysIlaWx_c',
    appId: '1:354431250194:ios:bf5a9300583cb5ff078dcb',
    messagingSenderId: '354431250194',
    projectId: 'jiffy-fuels',
    storageBucket: 'jiffy-fuels.appspot.com',
    androidClientId: '354431250194-gvpvca5pak9ud9kjed565kjjmn5uebjq.apps.googleusercontent.com',
    iosClientId: '354431250194-98l4pplekk3p0bgdf7j4sfu1ger2aqvc.apps.googleusercontent.com',
    iosBundleId: 'com.jiffyfuels.consumer.jiffyFuelsConsumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASD-aApWDb_EpnpmVLIJPx93ysIlaWx_c',
    appId: '1:354431250194:ios:bf5a9300583cb5ff078dcb',
    messagingSenderId: '354431250194',
    projectId: 'jiffy-fuels',
    storageBucket: 'jiffy-fuels.appspot.com',
    androidClientId: '354431250194-gvpvca5pak9ud9kjed565kjjmn5uebjq.apps.googleusercontent.com',
    iosClientId: '354431250194-98l4pplekk3p0bgdf7j4sfu1ger2aqvc.apps.googleusercontent.com',
    iosBundleId: 'com.jiffyfuels.consumer.jiffyFuelsConsumer',
  );
}
